/*
 * LauncherFrame.java
 *
 * Created on May 3, 2006, 2:06 PM
 */

package org.jdesktop.lg3d.apps.launcher;

import java.io.IOException;
import org.jdesktop.lg3d.scenemanager.config.ApplicationDescription;
import org.jdesktop.lg3d.utils.action.AppLaunchAction;

/**
 *
 * @author  krishnag
 */
public class LauncherFrame extends javax.swing.JFrame {
    
    ApplicationDescription appDesc;

    /** Creates new form LauncherFrame */
    public LauncherFrame() {
        initComponents();
	appDesc = new ApplicationDescription();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        launcherName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        launcherDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        launcherCommand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        launcherClasspath = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        launcherIcon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        launcherLaunch = new javax.swing.JButton();
        launcherSave = new javax.swing.JButton();
        launcherCancel = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Launcher");
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Launcher properties"));
        jLabel1.setText("Name");
        jPanel2.add(jLabel1);

        jPanel2.add(launcherName);

        jLabel2.setText("Description");
        jPanel2.add(jLabel2);

        jPanel2.add(launcherDescription);

        jLabel3.setText("Command");
        jPanel2.add(jLabel3);

        jPanel2.add(launcherCommand);

        jLabel4.setText("Classpath");
        jPanel2.add(jLabel4);

        jPanel2.add(launcherClasspath);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        launcherIcon.setIcon(new javax.swing.ImageIcon("/ws/krishnag/ws/java.net/lg3d/lg3d-demo-apps/src/classes/org/jdesktop/lg3d/apps/tutorial/resources/images/icon/launcher.png"));
        launcherIcon.setText("Choose Icon");
        jPanel4.add(launcherIcon);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setInheritsPopupMenu(true);
        launcherLaunch.setText("Launch");
        launcherLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launcherLaunchActionPerformed(evt);
            }
        });

        jPanel3.add(launcherLaunch);

        launcherSave.setText("Save");
        jPanel3.add(launcherSave);

        launcherCancel.setText("Cancel");
        launcherCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launcherCancelActionPerformed(evt);
            }
        });

        jPanel3.add(launcherCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launcherCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launcherCancelActionPerformed
// TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_launcherCancelActionPerformed

    private void launcherLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launcherLaunchActionPerformed
// TODO add your handling code here:
	appDesc.setName(launcherName.getText());
	appDesc.setDescription(launcherDescription.getText());
	
	if (!launcherClasspath.equals("")) {
	    try {
		appDesc.setClasspathJars(launcherClasspath.getText());
	    } catch (IOException ioe) {
		ioe.printStackTrace();
	    }
	}

	AppLaunchAction appLaunch = new AppLaunchAction(launcherCommand.getText(), appDesc.getClassLoader());
	appLaunch.performAction(null);
    }//GEN-LAST:event_launcherLaunchActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton launcherCancel;
    private javax.swing.JTextField launcherClasspath;
    private javax.swing.JTextField launcherCommand;
    private javax.swing.JTextField launcherDescription;
    private javax.swing.JButton launcherIcon;
    private javax.swing.JButton launcherLaunch;
    private javax.swing.JTextField launcherName;
    private javax.swing.JButton launcherSave;
    // End of variables declaration//GEN-END:variables
    
}
